version: '3.8'

services: 
  mini-filesystem:  
    build: "./mini-filesystem"
    container_name: mini-filesystem
    ports:
      - "8080:8080" 
    environment:
      - DB_HOST=postgres  
      - DB_PORT=5432
      - DB_NAME=filesystem
      - DB_USER=postgres
      - DB_PASSWORD=admin1234
    depends_on:
      postgres:
        condition: service_healthy  

  postgres:  
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: filesystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 10s  
      timeout: 5s    
      retries: 5      

  vue-frontend:  
    build: "./mini-filesystem-front/mini-filesystem"  
    container_name: vue-frontend
    ports:
      - "8081:8081" 
