FROM maven:3.6.3-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests


FROM openjdk:17-jdk
WORKDIR /app
COPY --from=build /app/target/mini-filesystem-0.0.1-SNAPSHOT.jar /app/mini-filesystem.jar
CMD ["java", "-jar", "/app/mini-filesystem.jar"]